"""
Configuration module for renalprog package.

Contains paths, hyperparameters, and constants used throughout the pipeline.
"""

from pathlib import Path
from datetime import datetime

# Project root directory
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Data directories
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
EXTERNAL_DATA_DIR = DATA_DIR / "external"

# Model directories
MODELS_DIR = PROJECT_ROOT / "models"

# Output directories
REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

# Notebook directory
NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"

# References directory
REFERENCES_DIR = PROJECT_ROOT / "references"

# Scripts directory
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
R_SCRIPTS_DIR = SCRIPTS_DIR / "r_analysis"
PIPELINE_SCRIPTS_DIR = SCRIPTS_DIR / "pipeline_steps"

# PATHS dictionary for easy access
PATHS = {
    "root": PROJECT_ROOT,
    "data": DATA_DIR,
    "raw": RAW_DATA_DIR,
    "interim": INTERIM_DATA_DIR,
    "processed": PROCESSED_DATA_DIR,
    "external": EXTERNAL_DATA_DIR,
    "models": MODELS_DIR,
    "reports": REPORTS_DIR,
    "figures": FIGURES_DIR,
    "notebooks": NOTEBOOKS_DIR,
    "references": REFERENCES_DIR,
    "scripts": SCRIPTS_DIR,
    "r_scripts": R_SCRIPTS_DIR,
    "pipeline_scripts": PIPELINE_SCRIPTS_DIR,
}


def get_dated_dir(base_dir: Path, prefix: str = "") -> Path:
    """
    Create a dated directory for organizing outputs.

    Args:
        base_dir: Base directory path
        prefix: Optional prefix for the directory name

    Returns:
        Path to the dated directory
    """
    today = datetime.now().strftime("%Y%m%d")
    if prefix:
        dir_name = f"{today}_{prefix}"
    else:
        dir_name = today
    dated_dir = base_dir / dir_name
    dated_dir.mkdir(parents=True, exist_ok=True)
    return dated_dir


# KIRC Data paths (to be set by user or config file)
class KIRCPaths:
    """Paths for KIRC-specific data files."""

    # Raw data from TCGA Xena Browser (user downloads manually)
    RNASEQ_RAW = RAW_DATA_DIR / "KIRC" / "HiSeqV2.gz"
    CLINICAL_RAW = RAW_DATA_DIR / "KIRC" / "KIRC_clinicalMatrix.gz"
    PHENOTYPE_RAW = RAW_DATA_DIR / "KIRC" / "KIRC_phenotype.gz"

    # Preprocessed data (generated by pipeline)
    RNASEQ_PREPROCESSED = None  # Set during runtime
    CLINICAL_PREPROCESSED = None  # Set during runtime

    # Important genes for classification
    IMPORTANT_GENES_50 = EXTERNAL_DATA_DIR / "50_important_genes_for_KIRC.csv"
    IMPORTANT_GENES_80 = EXTERNAL_DATA_DIR / "80_important_genes_for_KIRC.csv"
    FINAL_GENES_CLASSIFICATION = EXTERNAL_DATA_DIR / "final_genes_classification.csv"

    # Pathway databases
    REACTOME_PATHWAYS = EXTERNAL_DATA_DIR / "ReactomePathways.gmt"
    KEGG_PATHWAYS = EXTERNAL_DATA_DIR / "c2.cp.kegg_legacy.v2025.1.Hs.symbols.gmt"

    # Gene mapping
    BIOMART_GENES = EXTERNAL_DATA_DIR / "biomart_human_genes_GRCh37.p13.txt"


# VAE Hyperparameters
class VAEConfig:
    """Default hyperparameters for VAE training."""

    # Architecture
    INPUT_DIM = None  # Set based on data
    MID_DIM = 1024  # Middle layer dimension
    LATENT_DIM = 16  # Latent space dimension
    OUTPUT_ACTIVATION = "ReLU"  # Output activation function

    # Training
    LEARNING_RATE = 1e-4
    BATCH_SIZE = 8
    SEED = 2023

    # Loss parameters - Beta Annealing (Cyclical)
    BETA = 1.0  # Final/maximum weight for KL divergence term (beta-VAE)
    USE_BETA_ANNEALING = True  # Whether to use cyclical beta annealing
    BETA_START = 0.0  # Starting beta value (default 0.0)
    BETA_CYCLES = 3  # Number of annealing cycles
    EPOCHS = 100  # Number of epochs per annealing cycle
    BETA_RATIO = 0.5  # Ratio of cycle spent increasing (0.5 = half cycle increase, half constant)

    # Model type
    MODEL_TYPE = "VAE"  # Options: VAE, CVAE, AE

    # Checkpointing
    CHECKPOINT_FREQ = 10  # Save checkpoint every N epochs (0 = only best)
    SAVE_BEST = True  # Save best model based on validation loss
    SAVE_FINAL = True  # Save final model after training

    # Device
    DEVICE = "cpu"  # Will be set to "cuda" if available


# Preprocessing parameters
class PreprocessingConfig:
    """Parameters for data preprocessing."""

    # Low expression filtering
    MEAN_EXPRESSION_THRESHOLD = 0.5
    VAR_EXPRESSION_THRESHOLD = 0.5
    MIN_SAMPLE_FRACTION = (
        0.2  # genes must be expressed in at least this fraction of samples
    )

    # Mahalanobis outlier detection
    MAHALANOBIS_CONTAMINATION = 0.1  # Fraction of outliers expected

    # Train/test split
    TEST_SIZE = 0.2
    RANDOM_STATE = 2023

    # Stage mapping
    STAGE_MAPPING = {
        "Stage I": "early",
        "Stage II": "early",
        "Stage III": "late",
        "Stage IV": "late",
    }


# Trajectory generation parameters
class TrajectoryConfig:
    """Parameters for synthetic trajectory generation."""

    # Number of interpolation points between source and target patients
    N_SAMPLES = 50

    # Interpolation method
    INTERPOLATION_METHOD = "linear"  # Options: linear, spherical

    # Parallel processing
    N_WORKERS = None  # Will use os.cpu_count() if None

    # Trajectory types
    TRANSITIONS = ["early_to_late", "early_to_early", "late_to_late"]


# Classification parameters
class ClassificationConfig:
    """Parameters for stage classification."""

    # XGBoost parameters
    NUM_BOOST_ROUND = 100
    N_FOLDS = 10
    LEARNING_RATE = 0.1
    MAX_DEPTH = 6

    # Feature sets
    USE_ALL_GENES = True
    USE_IMPORTANT_GENES = True


# Enrichment analysis parameters
class EnrichmentConfig:
    """Parameters for pathway enrichment analysis."""

    # Gene clustering
    N_CLUSTERS = 10
    CLUSTERING_METHOD = "kmeans"

    # GSEA parameters
    PERMUTATIONS = 1000
    MIN_SIZE = 15
    MAX_SIZE = 500

    # Significance threshold
    FDR_THRESHOLD = 0.05
    PVALUE_THRESHOLD = 0.05


# Logging configuration
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


def ensure_directories():
    """Create all necessary directories if they don't exist."""
    dirs = [
        DATA_DIR,
        RAW_DATA_DIR,
        INTERIM_DATA_DIR,
        PROCESSED_DATA_DIR,
        EXTERNAL_DATA_DIR,
        MODELS_DIR,
        REPORTS_DIR,
        FIGURES_DIR,
        NOTEBOOKS_DIR,
        REFERENCES_DIR,
        SCRIPTS_DIR,
        R_SCRIPTS_DIR,
        PIPELINE_SCRIPTS_DIR,
    ]
    for dir_path in dirs:
        dir_path.mkdir(parents=True, exist_ok=True)


# Initialize directories on import
ensure_directories()

# Export public API
__all__ = [
    # Paths
    "PROJECT_ROOT",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "INTERIM_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "EXTERNAL_DATA_DIR",
    "MODELS_DIR",
    "REPORTS_DIR",
    "FIGURES_DIR",
    "NOTEBOOKS_DIR",
    "REFERENCES_DIR",
    "SCRIPTS_DIR",
    "R_SCRIPTS_DIR",
    "PIPELINE_SCRIPTS_DIR",
    "PATHS",
    # Functions
    "get_dated_dir",
    "ensure_directories",
    # Classes
    "KIRCPaths",
    "VAEConfig",
]
